[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'skywind3000/gutentags_plus'

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
