[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'Shougo/unite-build'

[[plugins]]
repo = 'tsukkee/unite-help'

[[plugins]]
repo = 'yomi322/vim-gitcomplete'
on_ft = 'vimshell'

[[plugins]]
repo = 'ujihisa/vimshell-ssh'
on_ft = 'vimshell'

[[plugins]]
repo = 'osyo-manga/unite-filetype'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:python3_host_prog = expand('/bin/python3.6')
  let g:deoplete#enable_at_startup = 1
'''

