[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'Shougo/unite-build'

[[plugins]]
repo = 'tsukkee/unite-help'

[[plugins]]
repo = 'yomi322/vim-gitcomplete'
on_ft = 'vimshell'

[[plugins]]
repo = 'ujihisa/vimshell-ssh'
on_ft = 'vimshell'

[[plugins]]
repo = 'osyo-manga/unite-filetype'

[[plugins]]
repo = 'tpope/vim-fugitive'

